# Generated by Django 4.1.5 on 2023-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Book name')),
                ('author', models.CharField(max_length=200, verbose_name='Book author')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('book_hash', models.UUIDField(verbose_name='Book Hash')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
