# Generated by Django 4.1.5 on 2023-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_hash',
            field=models.CharField(max_length=10, verbose_name='Book Hash'),
        ),
    ]
