# Generated by Django 4.1.5 on 2023-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_book_book_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_hash',
            field=models.CharField(blank=True, max_length=10, verbose_name='Book Hash'),
        ),
    ]
